spring:
  application:
    name: totoro-demo
  profiles:
    active: test
    include: common

server:
  port: 9101

mybatis-plus:
  typeAliasesPackage: org.totoro.demo.entity
  global-config:
    banner: false
    db-config:
      #主键类型  0:AUTO:"数据库ID自增", 1: NONE:"未设置主键类型",2:"INPUT", 3:ASSIGN_ID当没有手动设置主键，才会自动填充，使用雪花算法, 4:ASSIGN_UUID全局唯一ID (UUID);
      id-type: AUTO
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0

management:
  server:
    port: 19101