spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changlf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: chang123
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis1244656FYKJ508HzBJYfdxFyZn # 密码（默认为空）
    timeout: 10000
  elasticsearch:
    uris: https://127.0.0.1:9200
    api-key: TVVvRzBJMEJYR29RMjJrQTdlenA6NHk4Q0ppdTRSdDJ5eUI2U3lJLWZUZw==
    ssl-key-store: /certs/http_ca.crt

filter:
  aesDecryptFilter:
    enable: false
    excludedUris: /actuator*
  requestTrackFilter:
    enable: true
    excludedUris: /actuator*

logging:
  level:
    org.totoro: DEBUG
